; Common settings for all builds
[env]
board = rosbot_xl_digital_board ; same MCU config for both rosbot2 and XL
framework = arduino
platform = https://github.com/husarion/platformio_boards#1.0.0
platform_packages = framework-arduinoststm32 @ https://github.com/husarion/Arduino_Core_STM32

board_build.mcu = stm32f407zgt6
board_build.f_cpu = 168000000L
upload_protocol = stlink
; upload_protocol = serial
monitor_speed = 460800
debug_tool = stlink

lib_deps =
    https://github.com/stm32duino/LwIP#2.1.2
    https://github.com/husarion/STM32Ethernet#1.0.0
    https://github.com/micro-ROS/micro_ros_arduino#v2.0.7-humble
    https://github.com/stm32duino/STM32FreeRTOS#10.3.1
    https://github.com/husarion/PixelLedLib#1.0.0
    https://github.com/adafruit/Adafruit_Sensor#1.1.7
    https://github.com/adafruit/Adafruit_BNO055#1.6.1
    https://github.com/adafruit/Adafruit_BusIO#1.14.0

build_flags =
    -L ./.pio/libdeps/olimex_e407/micro_ros_arduino/src/cortex-m4/
    -l microros
    -I ./src
    -D ETHERNET_USE_FREERTOS
    -D TARGET_STM32F4
    -D LAN9303
    -Wfatal-errors


; rosbot_XL specific settings
[env:digital_board]
build_flags =
    ${env.build_flags}
    -D SERIAL_UART_INSTANCE=1
    -D DIGITAL_BOARD


; rosbot_2 specific settings
[env:core2]
build_flags =
    ${env.build_flags}
    -D SERIAL_UART_INSTANCE=3 ; Using this definition alone results in no communication, for some reason the Serial.setTx needs to be called manually!
    -D CORE_2
