; ==========================================================
; Base ENV shared for all boards
; ==========================================================
[env]
framework = arduino
board = rosbot_xl_digital_board
platform = https://github.com/husarion/platformio_boards#1.0.0
platform_packages = framework-arduinoststm32 @ https://github.com/husarion/Arduino_Core_STM32

upload_protocol = stlink
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
debug_tool = stlink
debug_speed = 4000

lib_deps =
    https://github.com/stm32duino/LwIP#2.1.2
    https://github.com/husarion/STM32Ethernet#1.0.0
    https://github.com/micro-ROS/micro_ros_arduino#v2.0.7-humble
    https://github.com/stm32duino/STM32FreeRTOS#10.3.1
    https://github.com/husarion/PixelLedLib#1.0.0
    https://github.com/adafruit/Adafruit_Sensor#1.1.7
    https://github.com/adafruit/Adafruit_BNO055#1.6.1
    https://github.com/adafruit/Adafruit_BusIO#1.14.0
    https://github.com/pololu/vl53l0x-arduino#1.3.1

build_flags =
    -L .pio/libdeps/olimex_e407/micro_ros_arduino/src/cortex-m4/
    -l microros
    -I include
    -DETHERNET_USE_FREERTOS
    -DTARGET_STM32F4
    -DLAN9303
    -Wfatal-errors

; ==========================================================
; RELEASE FLAGS
; ==========================================================
[release_flags]
build_flags =
    -O2
    -flto
    -ffast-math
    -funroll-loops
    -funsafe-math-optimizations
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard


; ==========================================================
; ROSBOT XL (normal)
; ==========================================================
[env:rosbot_xl]
extends = env
build_src_filter =
  +<*>
  +<rosbot_xl/*>
  -<rosbot/*>

build_flags =
    ${env.build_flags}
    -D SERIAL_UART_INSTANCE=1
    -DROSBOT_XL

; ==========================================================
; ROSBOT XL (release)
; ==========================================================
[env:rosbot_xl_release]
extends = env:rosbot_xl
build_flags =
    ${env:rosbot_xl.build_flags}
    ${release_flags.build_flags}


; ==========================================================
; ROSBOT (normal)
; ==========================================================
[env:rosbot]
extends = env
build_type = debug
; platform = ststm32
; board = rosbot
; platform_packages = framework-arduinoststm32 @ https://github.com/stm32duino/Arduino_Core_STM32
build_src_filter =
  +<*>
  +<rosbot/*>
  -<rosbot_xl/*>

build_flags =
    ${env.build_flags}
    -D SERIAL_UART_INSTANCE=3 ; Using this definition alone results in no communication, for some reason the Serial.setTx needs to be called manually!
    -DROSBOT

; ==========================================================
; ROSBOT (release)
; ==========================================================
[env:rosbot_release]
extends = env:rosbot
build_flags =
    ${env:rosbot.build_flags}
    ${release_flags.build_flags}
