; ──────────────────────────────────────────────────────────
; Base ENV shared for all boards
; ──────────────────────────────────────────────────────────
[env]
framework = arduino
board = rosbot_xl_digital_board
; board = rosbot
platform = https://github.com/husarion/platformio_boards#1.0.0
; platform = ststm32
platform_packages = framework-arduinoststm32 @ https://github.com/husarion/Arduino_Core_STM32
; platform_packages = framework-arduinoststm32 @ https://github.com/stm32duino/Arduino_Core_STM32

upload_protocol = stlink
monitor_speed = 921600
monitor_port = /dev/ttyUSB0
debug_tool = stlink
debug_speed = 4000

lib_deps =
    https://github.com/husarion/STM32Ethernet#1.0.0
    https://github.com/stm32duino/LwIP#2.1.3
    https://github.com/micro-ROS/micro_ros_arduino#v2.0.8-jazzy
    https://github.com/stm32duino/STM32FreeRTOS#10.3.3
    https://github.com/adafruit/Adafruit_Sensor#1.1.15
    https://github.com/adafruit/Adafruit_BNO055#1.6.4
    https://github.com/adafruit/Adafruit_BusIO#1.14.0
    https://github.com/pololu/vl53l0x-arduino#1.3.1

build_unflags =
    -std=gnu++14

build_flags =
    -std=gnu++17
    -l microros
    -I include
    -D TARGET_STM32F4
    -D FW_VERSION=\"1.0.0\"
    -Wall
    -Wextra
    -Wfatal-errors
    -Wmissing-field-initializers
    -Wno-deprecated-declarations # Ignore deprecation warnings from the libraries we use

; ──────────────────────────────────────────────────────────
; Release optimization flags
; ──────────────────────────────────────────────────────────
[release_flags]
build_flags =
    -O2
    -flto
    -ffast-math
    -funroll-loops
    -funsafe-math-optimizations
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard

; ──────────────────────────────────────────────────────────
; ROSBOT
; ──────────────────────────────────────────────────────────
[env:rosbot]
extends = env
build_src_filter =
  +<rosbot/*>
  -<rosbot_xl/*>
build_flags =
    ${env.build_flags}
    -D ENABLE_HWSERIAL1
    -D ENABLE_HWSERIAL3
    -D ROSBOT

[env:rosbot_release]
extends = env:rosbot
build_flags =
    ${env:rosbot.build_flags}
    ${release_flags.build_flags}


; ──────────────────────────────────────────────────────────
; ROSBOT XL
; ──────────────────────────────────────────────────────────
[env:rosbot_xl]
build_src_filter =
  -<rosbot/*>
  +<rosbot_xl/*>
extends = env
build_flags =
    ${env.build_flags}
    -D ENABLE_HWSERIAL1
    -D ENABLE_HWSERIAL3
    -D ROSBOT_XL

[env:rosbot_xl_release]
extends = env:rosbot_xl
build_flags =
    ${env:rosbot_xl.build_flags}
    ${release_flags.build_flags}
